GHQ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('GhqApp.urls')),
    path('',include('UserApp.urls'))
]

GhqApp/urls.py
from django.urls import path
from .views import QuestionDisplayView, ResultView

app_name = 'ghq_app'

urlpatterns = [ 
    path('questions/', QuestionDisplayView.as_view(), name='questions'),
    path('result/<str:quiz_taken>/',ResultView.as_view(), name='result')
]

UserApp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, HomeView
from GHQ import settings

app_name = 'user_app'

urlpatterns = [ 
    path('', HomeView.as_view(), name='home'),
    path('accounts/register/', SignUpView.as_view(), name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='new_login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block css %}
        <link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'assets/css/custom-style.css' %}" rel="stylesheet" type="text/css" />
        {% endblock css %}
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    

    {% block content %}
    <!-- header start -->
    <div>
    <ul class="nav bg-dark ">
        <ul class="nav ml-auto nav-boldest">
            {% block redirect_home %}
            {% endblock redirect_home %}
            {% if user.is_authenticated %}
            
            <li class="nav-item p-3 ">
                <a class="nav-link active accounts text-white" href="#">Hi {{user.username}}</a>
                
            </li>
            {% if result != 0 %}
            <li class="nav-item p-3 ">
                
                    <a class="nav-link active accounts" href="{% url 'ghq_app:result' quiz_taken=result %}">
                        Results
                    </a>
                
                
            </li>
            {% endif %}
            <li class="nav-item p-3">
                <a href="{% url 'user_app:logout' %}" class="nav-link active accounts">
    
                    LOGOUT
                </a>
            </li>
            {% else %}
            {% block register %}
            <li class="nav-item p-3">
                <a href="{% url 'user_app:register' %}" class="nav-link active accounts" id="register">
                    SIGN UP
                </a>
            </li>
            {% endblock register %}
            {% block login %}
            <li class="nav-item p-3 bold text-white ">
                <a href="{% url 'user_app:login' %}" class="nav-link active accounts" id="login">
                    LOGIN
                </a>
            </li>
            {% endblock login %}
        </ul>
        {% endif %}
    
    </ul>
</div>
    <!-- header end -->
    {% endblock content %}

    {% block javascripts %}
        
		<script>var HOST_URL = "https://preview.keenthemes.com/metronic/theme/html/tools/preview";</script>
		<script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#6993FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#F3F6F9", "dark": "#212121" }, "light": { "white": "#ffffff", "primary": "#E1E9FF", "secondary": "#ECF0F3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#212121", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#ECF0F3", "gray-300": "#E5EAEE", "gray-400": "#D6D6E0", "gray-500": "#B5B5C3", "gray-600": "#80808F", "gray-700": "#464E5F", "gray-800": "#1B283F", "gray-900": "#212121" } }, "font-family": "Poppins" };</script>
		<script src="  {% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
		<script src="  {% static 'assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
		<script src="  {% static 'assets/js/scripts.bundle.js' %}"></script>
        {% endblock javascripts %}
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
HOME
{% endblock title %}
{% load static %}
{% block css %}
{{block.super}}
<link href="{% static 'local_css/home.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}


{% block content %}
{{block.super}}

<div id="mental_health">
    <div class=" description d-flex flex-column justify-content-center">
        <div class="  heading  mb-4">Mental Health Matters</div>
        
        <div class="text-center">
        <a  class="btn btn-secondary " style="width: 180px; height: 60px; text-align: center; line-height: 40px; font-weight: bolder;" href="{% url 'ghq_app:questions' %}">
            TAKE A TEST
         </a>
        </div>
        <div class="text-white bold mt-5 sponsor">
            Sponsored by Dr. Ashit Sheth
         </div>
    </div>
   
</div>


{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{{block.super}}
<link href="{% static 'local_css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}
{% block title %} LOG IN {% endblock title %}

{% load crispy_forms_tags %}
{% block content %}



<div class="d-flex flex-row justify-content-center">

    <div class="form">

        <div class="d-flex flex-column justify-content-center">
            <div class="">
                <h2>LOGIN</h2>
            </div>

            <div class="mt-4 " id="login_form">
                <form method="POST" class="" id = "kt_login_signin_form">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-secondary">LOGIN</button>
                </form>
            </div>
            <div class="border-top pt-5 mt-2">
                <small class="text-muted">
                    Dont Have an account ? <a href="{% url 'user_app:register' %}" class="active">Sign Up</a>

                </small>
            </div>

        </div>

    </div>
    <div>
        <img src="{% static 'assets/media/svg/illustrations/features.svg' %}" id="login_svg" >

    </div>
</div>
{% endblock content %}
{% block javascripts %}
{{block.super}}
{% endblock javascripts %}

templates/logout.html
   
{% extends 'base.html' %}
{% block title %}Logout{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h3>Logged out Successfully</h3>
   <div>
       <h4>
           Want to Login Again ? <a class=" active" href="{% url 'user_app:login' %}">Login</a>
        </a> or Go to <a class="active" href="{% url 'user_app:home' %}">HOME</a>
       </h4>
   </div>
</div>
{% endblock content %}

templates/new_login.html
{% extends 'base.html' %}
{% block redirect_home %}
		<li class="nav-item p-3">
			<a href="{% url 'user_app:home' %}" class="nav-link active accounts">

				HOME
			</a>
		</li>
		
{% endblock redirect_home %}
{% block login %}
{% endblock login %}
{% block register %}
		{{block.super}}
		{% endblock register %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
{{block.super}}
		<link href="{% static 'assets/css/pages/login/login-1.css' %}" rel="stylesheet" type="text/css" />
{% endblock css  %}

		{% block content %}
		
		{{block.super}}
		<div class="d-flex flex-column flex-root">
			<!--begin::Login-->
			<div class="login login-1 login-signin-on d-flex flex-column flex-lg-row flex-column-fluid bg-white" id="kt_login">
				<!--begin::Content-->
				<div class="login-content flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
					<!--begin::Content body-->
					<div class="d-flex flex-column-fluid flex-center">
						<!--begin::Signin-->
						<div class="login-form login-signin">
							<!--begin::Form-->
							<form class="form" method="POST" >
                                <h1 class="text-center">LOGIN</h1>
                                {% csrf_token %}
								{{form|crispy}}
								<div class="d-flex">
									<div>
                                <button class="btn btn-primary"> LOGIN </button>
							</div>
							<div class="text-muted mt-3 ml-4">
								Don't have an account? <a href="{% url 'user_app:register' %}">Register</a>
							</div>
								</div>
								<!--end::Action-->
							</form>
							<!--end::Form-->
						</div>
						<!--end::Signin-->
					</div>
					<!--end::Content body-->
					<!--begin::Content footer-->
					
					<!--end::Content footer-->
				</div>
				<!--end::Content-->
				<!--begin::Aside-->
				<div class="login-aside d-flex flex-column flex-row-auto" style="background-color: #FCFFF1;">
					<!--begin::Aside Top-->
					<div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
						
					</div>
					<!--end::Aside Top-->
					<!--begin::Aside Bottom-->
					<div class="aside-img d-flex flex-row-fluid bgi-no-repeat bgi-position-y-bottom bgi-position-x-center" style="background-image: url('{% static 'assets/media/svg/illustrations/features.svg' %}')"></div>
					<!--end::Aside Bottom-->
				</div>
				<!--begin::Aside-->
			</div>
			<!--end::Login-->
		</div>
		{% endblock content %}
		
		{% block javascripts %}
		{{block.super}}
		<script src="{% static 'assets/js/pages/custom/login/login-general.js' %}"></script>
		{% endblock javascripts %}

templates/new_signup.html
{% extends 'base.html' %}
{% block redirect_home %}
		<li class="nav-item p-3">
			<a href="{% url 'user_app:home' %}" class="nav-link active accounts">

				HOME
			</a>
		</li>
{% endblock redirect_home %}
{% block register %}
{% endblock register %}
{% block login %}
{{block.super}}
{% endblock login %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
{{block.super}}
<link href="{% static 'assets/css/pages/login/login-1.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}
		{% block content %}
		{{block.super}}
		<div class="d-flex flex-column flex-root">
			<!--begin::Login-->
			<div class="login login-1 login-signin-on d-flex flex-column flex-lg-row flex-column-fluid bg-white" id="kt_login">
				<!--begin::Content-->
				<div class="login-content flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
					<!--begin::Content body-->
					<div class="d-flex flex-column-fluid flex-center">
						<!--begin::Signin-->
						<div class="login-form login-signin">
							<!--begin::Form-->
							<form class="form" method="POST" >
                                <h1 class="text-center">New User Registration</h1>
                                {% csrf_token %}
								{{form|crispy}}
								<div class="d-flex">
									<div>
                                <button class="btn btn-primary"> Resigter </button>
							</div>
							<div class="text-muted mt-3 ml-4">
								Already have an account? <a href="{% url 'user_app:login' %}">Login</a>
							</div>
								</div>
								<!--end::Action-->
							</form>
							<!--end::Form-->
						</div>
						<!--end::Signin-->
					</div>
					<!--end::Content body-->
					<!--begin::Content footer-->
					
					<!--end::Content footer-->
				</div>
				<!--end::Content-->
				<!--begin::Aside-->
				<div class="login-aside d-flex flex-column flex-row-auto" style="background-color: #FCFFF1;">
					<!--begin::Aside Top-->
					<div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
						
					</div>
					<!--end::Aside Top-->
					<!--begin::Aside Bottom-->
					<div class="aside-img d-flex flex-row-fluid bgi-no-repeat bgi-position-y-bottom bgi-position-x-center" style="background-image: url('{% static 'assets/media/svg/illustrations/login-visual-5.svg' %}')"></div>
					<!--end::Aside Bottom-->
				</div>
				<!--begin::Aside-->
			</div>
			<!--end::Login-->
		</div>


		
		
		{% endblock content %}
		
		{% block javascripts %}
		{{block.super}}
		<script src="{% static 'assets/js/pages/custom/login/login-general.js' %}"></script>
		{% endblock javascripts %}

templates/question.html
{% extends 'base.html' %}
{% block redirect_home %}
		
{% endblock redirect_home %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} QUESTION {% endblock title %}
{% block css %}
{{block.super}}
<link href="{% static 'local_css/question.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}
{% block content %}



<form method="POST" class="container py-5 rounded">

    {% csrf_token %}

   
    <div class="card card-custom">
        <div class="card-header">
         <div class="card-title">
                   <span class="card-icon">
                       <i class="flaticon2-chat-1 text-primary"></i>
                   </span>
          <h1 class="card-label">
            {{question}}
           
          </h1>
         </div>
            <div class="card-toolbar text-muted">
                Question {{current_question_number}} of {{total_questions}}
            </div>
        </div>
        <div class="card-body">
            <div class="radio-list ">
                <div class="option">{{form.user_answer.0}}</div>
                <div class="option">{{form.user_answer.1}}</div>
                <div class="option">{{form.user_answer.2}}</div>
                <div class="option">{{form.user_answer.3}}</div>


            </div>
        </div>
           <div class="card-footer d-flex justify-content-center">
               
            <button type="submit" class="btn btn-success ">{{submit_button_name}}</button>
        </div>
    </div>

</form>

{% endblock content %}
{% block javascripts %}
<script src="{% static 'local_javascript/question.js' %}"></script>
{% endblock javascripts %}

templates/result.html
{% extends 'base.html' %}
{% load social_share %}
{% load static %}
{% block css %}
{{block.super}}
<link href="{% static 'local_css/result.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}
{% block title %} RESULT {% endblock title %}
{% block content %}

<div class="container py-5 rounded ">
    <div class="card card-custom ">
        <div class="card-header d-flex justify-content-center">
            <div class="card-title ">
                <h3 class="card-title align-items-start flex-column">
                    <span class="card-label font-weight-bolder text-dark "><h1>Result</h1></span>
                </h3>
            </div>
            <div class="card-toolbar" id="card_header">
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered text-center" id="kt_datatable">
                <thead class="thead-dark">
                    <tr>
                        <th scope='col' style="width: 40%;"> Question </th>
                        <th scope='col' style="width: 30%;"> Answer </th>
                        <th scope='col'> Score </th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div>
                <a class="btn btn-light-success mr-2" href="{% url 'user_app:home' %}?retest=True">
                    RETEST
                </a>
            </div>
            
                {% if save == True %}
                <div id="save" class="mr-2 ">
                    <a href="{% url 'user_app:register' %}" class="btn btn-warning ">
                  SAVE
                    </a>
                </div>
                {% endif %}
            <div class="d-flex flex-row justify-content-center" id="share">
                <div id="whatsapp" class="mr-2 align-middle mt-2">
                    {% post_to_whatsapp object_or_url "Share via WhatsApp" %}
                </div>
                <div id="email" class="mr-2 align-middle mt-2">
                    {% send_email object.title "My test result : hi Check it out!" object_or_url "Share via email" %}
                </div>
                <div id="total_score align-middle">
                    <a class="btn btn-light-success"><span class="text-dark" id="score">Score: {{marks_achieved}}</span></a>
                </div>
                
            </div>

        </div>
    </div>
    {% if marks_achieved > 11  %}
    <div class="heart-age">
        <div class="age text-danger">{{marks_achieved}}</div>
        <p><strong>Your Score is   {{marks_achieved}}</strong><br><br>Based on the answers given by you </p>
                <p>
                There might be a chance that you may be psychologically  distressed. We would advice you to  consult a psychotherapist or psychiatrist.
            </p>
        </div>
    {% else %}
    <div class="heart-age">
        <div class="age" style="color: green;">{{marks_achieved}}</div>
        <p><strong>Your Score is   {{marks_achieved}}</strong><br><br>Based on the answers given by you </p>
                <p>
                There might be less chance that you may be psychologically  distressed. We would recommned you to stay healthy and happy &#128512;
            </p>
        </div>
    {% endif %}
    
    {% if user.is_authenticated %}
    {% if user.username == username %}

    <div class="py-5">
        <div class="row justify-content-around" id="other_results">

        </div>
    </div>




    {% endif %}
    {% endif %}
</div>



{% endblock content %}


{% block javascripts %}
{{block.super}}
<script>
    const data = JSON.parse(("{{data|escapejs}}"))
</script>
<script src="{% static 'local_javascript/result.js' %}">

</script>
{% endblock javascripts %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{{block.super}}
<link href="{% static 'local_css/signup.css'  %}"  rel="stylesheet" type="text/css" >
{% endblock css %}
{% load crispy_forms_tags %}
{% block title %} REGISTER {% endblock title %}
{% block content %}
{{block.super}}



<div class="container">

    <div class="d-flex flex-column justify-content-center">
        <div>
        <h3 class="text-center">SIGN UP</h3>
        </div>
        <div class="mt-3">
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-success">SUBMIT</button>
            
            </form>
        </div>
        <div class="border-top pt-5 mt-2">
            <small class="text-muted">
                Already have an account ? <a href="{% url 'user_app:login' %}" class="active">Sign in</a>

            </small>
        </div>
    </div>
    

</div>
{% endblock content %}